In [1]:
import tensorflow as tf

In [2]:
image=tf.io.read_file('/content/WhatsApp Image 2025-06-01 at 3.12.04 PM.jpeg')

In [3]:
th=tf.image.decode_image(image,channels=3)

In [4]:
th

<tf.Tensor: shape=(527, 456, 3), dtype=uint8, numpy=
array([[[238, 232, 216],
        [238, 232, 216],
        [238, 232, 216],
        ...,
        [254, 248, 232],
        [254, 248, 232],
        [254, 248, 232]],

       [[238, 232, 216],
        [238, 232, 216],
        [238, 232, 216],
        ...,
        [254, 248, 232],
        [254, 248, 232],
        [254, 248, 232]],

       [[238, 232, 216],
        [238, 232, 216],
        [238, 232, 216],
        ...,
        [254, 248, 232],
        [254, 248, 232],
        [254, 248, 232]],

       ...,

       [[ 46,  50,  27],
        [ 44,  48,  25],
        [ 41,  44,  23],
        ...,
        [215, 209, 193],
        [213, 207, 191],
        [213, 207, 191]],

       [[ 44,  48,  25],
        [ 42,  46,  23],
        [ 40,  43,  22],
        ...,
        [213, 207, 191],
        [212, 206, 190],
        [211, 205, 189]],

       [[ 42,  46,  23],
        [ 41,  45,  22],
        [ 39,  42,  21],
        ...,
        [212, 206, 19

In [5]:
th=th/255

In [6]:
th

<tf.Tensor: shape=(527, 456, 3), dtype=float32, numpy=
array([[[0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        ...,
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ]],

       [[0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        ...,
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ]],

       [[0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        [0.93333334, 0.9098039 , 0.84705883],
        ...,
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ],
        [0.99607843, 0.972549  , 0.9098039 ]],

       ...,

       [[0.18039216, 0.19607843, 0.10588235],
        [0.17

In [7]:
def conv_model():
  inputs=tf.keras.Input(shape=(527, 456, 3))
  l1=tf.keras.layers.Conv2D(filters=5,kernel_size=(3,3),strides=1,activation='relu')(inputs)
  model=tf.keras.models.Model(inputs=inputs,outputs=l1)
  return model


In [8]:
model=conv_model()

In [9]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 527, 456, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 525, 454, 5)    │           140 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 140 (560.00 B)

 Trainable params: 140 (560.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model_input=tf.expand_dims(th,axis=0)
model_input

<tf.Tensor: shape=(1, 527, 456, 3), dtype=float32, numpy=
array([[[[0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         ...,
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ]],

        [[0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         ...,
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ]],

        [[0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         [0.93333334, 0.9098039 , 0.84705883],
         ...,
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ],
         [0.99607843, 0.972549  , 0.9098039 ]],

        ...,

        [[0.18039216, 0.19607843, 

In [11]:
y_pred=model(model_input)

In [12]:
y_pred

<tf.Tensor: shape=(1, 525, 454, 5), dtype=float32, numpy=
array([[[[0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         [0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         [0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         ...,
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ],
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ],
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ]],

        [[0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         [0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         [0.7848998 , 0.        , 0.522708  , 0.        , 0.3915257 ],
         ...,
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ],
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ],
         [0.8369027 , 0.        , 0.55936444, 0.        , 0.4174639 ]],

        [[0.7848998 , 0.        , 0.522708  , 0.        , 

In [13]:
model.layers

[<InputLayer name=input_layer, built=True>, <Conv2D name=conv2d, built=True>]

In [14]:
model.layers[0].weights

[]

In [15]:
model.layers[1].weights

[<Variable path=conv2d/kernel, shape=(3, 3, 3, 5), dtype=float32, value=[[[[ 0.25788575  0.01738918  0.03691503 -0.2640874  -0.2576303 ]
    [ 0.00584128 -0.1911937   0.10794806 -0.19964334  0.28523737]
    [-0.21413827 -0.11983761 -0.2758559   0.21848327  0.26311386]]
 
   [[ 0.27720767  0.13753197  0.17921558  0.16298121  0.02176842]
    [ 0.12461913  0.100337    0.01156697 -0.25909153  0.08160037]
    [ 0.14357945 -0.02419788  0.07609403 -0.09889242 -0.02808508]]
 
   [[ 0.0342769   0.16191813 -0.2862561   0.13363877  0.13246977]
    [ 0.12393272  0.2152791   0.25417942 -0.09700571  0.02920377]
    [-0.03109825  0.01318827 -0.06238399  0.22328174  0.25299555]]]
 
 
  [[[ 0.18112645 -0.08923662  0.10241237 -0.05056734 -0.07611875]
    [-0.22519894 -0.00562766  0.12393051 -0.11795998  0.22620791]
    [ 0.14260536 -0.18440206  0.19910732  0.1645594  -0.2457691 ]]
 
   [[-0.12166789 -0.25691822  0.24262303 -0.07880694 -0.03980681]
    [-0.08264658 -0.17707229 -0.18106121 -0.1549539  -0.